### ISSUE TITLE
Error browsing vignettes

### ISSUE THREAD

**Issue by biorelated** [jalvesaq/Nvim-R#271]
Is it possible to browse vignettes? I am running in to this error message. 
```
vignette("vignette_title")
starting httpd help server ... done
Error in .C("nvimcom_msg_to_vim", paste0("StartTxtBrowser(\"w3m\",\"",  :
C symbol name "nvimcom_msg_to_vim" not in load table
```

Any ideas on how to  resolve it?  Thank you.

**Comment by jalvesaq** [comment]
Regardless of using either Vim or Neovim, please, replace `nvimcom_msg_to_vim` with `nvimcom_msg_to_nvim` and try again.

**Comment by biorelated** [comment]
And where do I pass that instruction? or do I set it in the  init.vim script? 
Apologies, I am not very familiar with the code-base

**Comment by jalvesaq** [comment]
Probably you have set the `browser` option in your `~/.Rprofile`, but you should change the browser in that way only if you really want to use `w3m` inside `tmux` instead of a graphical browser (such as Firefox or Google-chrome).

**Comment by jalvesaq** [comment]
I guess the issue is solved... If not, please, reopen it.

**Comment by biorelated** [comment]
I have not set any browser options in my `~/.Rprofile`. I expected that the default graphical browser would be used to browse the vignettes. in addition, I am still not sure in which file `nvimcom_msg_to_nvim` should be set.

**Comment by jalvesaq** [comment]
What is your operating system? If you are using either Linux or Mac OS X, start a terminal emulator, goes to Nvim-R directory and do
```
grep -R nvimcom_msg_to_vim
```
and you will see that the string "nvimcom_msg_to_vim" does not exist there. If you do
```
grep -R nvimcom_msg_to_nvim
```
then you will see it being used at some places. If you do
```
grep -R w3m 
```
you will see that the string "w3m" only appears in `doc/Nvim-R.txt`. That is why I have assumed that you have copied the code from the documentation to your `~/.Rprofile`. I have guessed that you use Vim rather than Neovim and because of that you have thought that `nvimcom_msg_to_nvim` shoud be replaced with `nvimcom_msg_to_vim`. Please, do in Vim:
```
:h Nvim-R-Rprofile
```
Note: if you are using Windows, your R profile might be at `~/Documents/.Rprofile`.
