### ISSUE TITLE
Puzzled discrepancy

### ISSUE THREAD

**Issue by Tongzhoutz** [jalvesaq/Nvim-R#539]
I defined a function "done" to trim data. Use this function, I want to trim a handful of variables in my dataframe x, say AR14258,AR14259,AR14260,AR14261. 

However, when executed on Vim, the codes below trimmed ALL variables in the data frame x. I tried it on R studio which gave the correct outputs that only the four designated variables were trimmed. I wonder why the same codes can give different outputs.

done   <- function(x){
   x[x > 1] = NA
   return(x)
}

x   <- x %>% mutate(across(  c(AR14258,AR14259,AR14260,AR14261)   , done))

Also, another annoying problem I ran into is that error messages always pop up when over 50 lines of codes are executed at the same time. Almost all errors say that some commands or numbers cannot be identified correctly.  So, for a quite long codes, I have to execute it multiple times. Is this a common problem? thanks

**Comment by mschilli87** [comment]
Could you please provide a *full* **minimal** example that we can copy and paste into a file, run via `RScript` to get the expected output and via `Nvim-R` to see the unexpected output?

**Comment by Tongzhoutz** [comment]
> Could you please provide a _full_ **minimal** example that we can copy and paste into a file, run via `RScript` to get the expected output and via `Nvim-R` to see the unexpected output?

Here is an example:
`RR1234   <- rnorm(100, 2, 3)
RR5678    <-  rnorm(100,3,4)
RR0135    <- rnorm(100,4,5)  
x   <- data.frame(RR1234,RR5678,RR0135)

done   <- function(x){
   x[x > 1] = NA
   return(x)
}

x   <-  x %>% mutate(across(c(RR1234, RR5678), done))
summary(x$RR1234)
summary(x$RR5678)
summary(x$RR0135)`

By invoking `summary()`, Nvim-R trimmed ALL the three variables, while R studio only trimmed the two designated variables RR1234 and RR5678.

**Comment by mschilli87** [comment]
Not to be picky, but running this code results in

```
Error in x %>% mutate(across(c(RR1234, RR5678), done)) :
  could not find function "%>%"
Execution halted
```

While I can debug this myself, I really shouldn't need to.
Especially because if somebody else want to help you, they'd have to re-do it again.
All because you wouldn't feel the need to add

```r
# install.packages("dplyr")
library(dplyr)
```
to your example.

Running this followed by your code through RScript gives me

```
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.       NA's
-3.6184331 -1.7660270 -0.8085489 -0.8780518  0.3081482  0.9840490         68
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.       NA's
-8.3305510 -2.1057052 -0.1337232 -1.0649014  0.4427956  0.9112637         74
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-9.582538  1.348307  4.515856  3.944333  6.976883 10.652564
```

Opening the file in nvim, launching R via leader-R-F and running the code via leader-A-A gives me

```
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. NA's
-3.8038816 -2.1242221 -0.5132234 -0.8438024  0.3029777  0.9929739   58
       Min.     1st Qu.      Median        Mean     3rd Qu.        Max. NA's
-5.56605126 -2.51343293 -0.82010722 -1.37360638 -0.05405973  0.90634373   71
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.
-9.0392863  0.2884561  3.7162028  3.5181223  7.3435946 14.3390159
```

When I compared the output I only noticed they are different.
Going back to your code, I noticed the random calls without setting a seed.
So of course everytime I run this, I'll get something else.

So I ended up adding

```r
set.seed(19)
```

and re-running everything once more.

This time, `Rscript` gave me

```
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.       NA's
-5.1055636 -2.3802408 -0.9269389 -1.1602123  0.1562168  0.9731878         64
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.       NA's
-7.3259431 -3.1347840 -1.4295475 -1.8241103 -0.2461753  0.8451930         75
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-8.188096 -1.397640  3.415384  3.113548  7.041665 13.187132
```

and `Nvim-R`

```
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.       NA's
-5.1055636 -2.3802408 -0.9269389 -1.1602123  0.1562168  0.9731878         64
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.       NA's
-7.3259431 -3.1347840 -1.4295475 -1.8241103 -0.2461753  0.8451930         75
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
-8.188096 -1.397640  3.415384  3.113548  7.041665 13.187132
```

So AFAICT you get the exact same results using `R` directly and via `nvim`.
Thus, if RScript should behave differently, I would call that a bug in RStudio.

For completeness, here is my `test.R` file:


```r
library(dplyr)

set.seed(19)

RR1234 <- rnorm(100, 2, 3)
RR5678 <- rnorm(100,3,4)
RR0135 <- rnorm(100,4,5)
x <- data.frame(RR1234,RR5678,RR0135)

done <- function(x){
x[x > 1] = NA
return(x)
}

x <- x %>% mutate(across(c(RR1234, RR5678), done))
summary(x$RR1234)
summary(x$RR5678)
summary(x$RR0135)
```

**Comment by jalvesaq** [comment]
@mschilli87, thanks for requesting a working example and for fixing the sample code!
Running the code fixed by @mschilli87 I get exactly the same result, that is, only two variables have some values replaced with `NA`s. So, I can't replicate the issue reported by @Tongzhoutz: the function `done` is NOT applied to all variables in the data.frame.

**Comment by Tongzhoutz** [comment]
Thanks @mschilli87 and @jalvesaq , I also replicated the work example and got the same result. But the problem still persists when my codes is running. I am still working on it to figure out the glitch.

**Comment by jalvesaq** [comment]
By default, RStudio saves the workspace before quitting. This is a common source of trouble because some scripts will give different results if the .RData file is not loaded at R startup.

**Comment by jalvesaq** [comment]
I'm closing the issue, @Tongzhoutz. If you have ever discovered what was causing the problem, and if you still remember it, please, tell us.
