### ISSUE TITLE
Completion Issue - "Error detected while processing function CompleteR[94]"

### ISSUE THREAD

**Issue by emanuelealiverti** [jalvesaq/Nvim-R#583]
I got a completion issues sometimes.
I was able to create a reproducible example with the ggplot's `scale_*` functions. 

Setup: neovim v0.4.4 on OSX, using Nvim-R master's commit [commit 8e82f228090446d546a9993066713e663d4df536]. A similar issue was happening also on my previous Lubuntu machine, although I don't remember the precise error message

Steps to reproduce:

```r
library(ggplot2)
dd = data.frame(x=rnorm(100), y = rnorm(100))
dd$z = 1*(dd$x > 0)
ggplot(dd) + geom_point(aes(x,y, col = z)) + 
	scal
```
Launch R with `\rf`. Call completion for `scal` with `C-X C-O`. 
Result:

```
Error detected while processing function CompleteR[94]..WaitRCompletion[1]..ROnJobStdout:
line    7:
E115: Missing quote:

Error detected while processing function CompleteR[94]..WaitRCompletion[1]..ROnJobStdout:
line    7:
E116: Invalid arguments for function SetComplMenu
```

At the end of the error message, I also get this text displayed in the R console:

```
[ClientServer] Unknown command: 
```

**Comment by jalvesaq** [comment]
Could you, please, update Nvim-R and try again?

**Comment by jalvesaq** [comment]
Please, reopen if not fixed.

**Comment by emanuelealiverti** [comment]
Hi Jakson, thanks for your help and sorry for the late reply. Unfortunately it's still not working properly. I still get the same error. I also tried to type few more characters and call compilation on `scale_`.  

The full message I get is

```
Error detected while processing function CompleteR[94]..WaitRCompletion[1]..ROnJobStdout:
line    7:
E115: Missing quote: 'The ‘brewer’ scales provides sequential, diverging and qualitative colo
ur schemes from ColorBrewer. These are particularly well suited to display discrete values on
 a map. See https://colorbrewe
Error detected while processing function CompleteR[94]..WaitRCompletion[1]..ROnJobStdout:
line    7:
E116: Invalid arguments for function SetComplMenu
[ClientServer] Unknown command: r2.org for more information.'}},{'word': 'scale_color_gradien
t', 'menu': 'func [ggplot2]', 'user_data': {'cls': 'f', 'pkg': 'ggp [...]
```

**Comment by jalvesaq** [comment]
If you put `options(nvimcom.verbose = 1)` in your `~/.Rprofile` you will see nvimcom's version number on startup. It should be 0.9.109.

The omni completion of `scale_` is working here (Ubuntu):

![Omnicompletion_scale_](https://user-images.githubusercontent.com/891655/113290574-3bd71d00-92c8-11eb-9039-9a6025709357.png)

**Comment by emanuelealiverti** [comment]
I confirm I am using the most recent version. I have tried with a minimal vimrc file, as follows:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
```

![Apr-01-2021 14-46-53](https://user-images.githubusercontent.com/20012954/113295999-334b0a80-92f9-11eb-8e83-599860b57d12.gif)

**Comment by jalvesaq** [comment]
I could replicate the issue on Windows (virtual machine). It seems the bug only affects systems where the encoding is not UTF-8. I'll fix it later today or on Monday.

**Comment by jalvesaq** [comment]
It should be fixed now (it's working on Windows).

**Comment by emanuelealiverti** [comment]
I have updated to the current version but, unfortunately, I still get the same error.
As an attempt, I tried to downgrade to 0.9.82 and things seems to work well there

![Apr-01-2021 23-25-04](https://user-images.githubusercontent.com/20012954/113355936-cdcf3c00-9341-11eb-9190-73091ba33948.gif)

**Comment by jalvesaq** [comment]
Unfortunately, I can't fix the issue because I can't replicate it. So, we have to wait until someone fixes it and does a pull request.

**Comment by jalvesaq** [comment]
Did you start R after updating Nvim-R? It's necessary to start R to update the 'omnils_*' files. Now (since yesterday), Nvim-R deletes the old omnils files when there is a change in the file format to avoid a mismatch between the files saved in the cache directory and the currently valid format.

**Comment by emanuelealiverti** [comment]
Not sure. I will not be able to use osx for some weeks, and I am back using ubuntu currently (where things work well). 
I can provide some updates in a couple of weeks.

**Comment by emanuelealiverti** [comment]
I could reproduce the issue on Ubuntu. Same setup + nvimcom 0.9.111. I can confirm I have deleted the cache files manually to force a rebuild.

```r
scale_value = function(x, sd = T) scale(x, scale = sd)
scale
```
![image](https://user-images.githubusercontent.com/20012954/113986094-26746c80-984d-11eb-98ff-3457fb8a1c23.png)

**Comment by jalvesaq** [comment]
This is another issue, perhaps introduced when I fixed the other one. But it's fixed now.

**Comment by jalvesaq** [comment]
I could replicate the issue now. It happens when the completion list is too big. Then the buffer sent to Neovim is truncated and the dictionary represented by the text being transmitted becomes broken. The maximum buffer size seems to be smaller on a Mac system than on a Linux one, but I could replicate the bug on Linux trying to complete "s" after the following code:

```r
library("dplyr")
library("ggplot2")
library("Hmisc")
library("psych")
```

**Comment by andyquinterom** [comment]
So any fix on MacOS?

**Comment by jalvesaq** [comment]
Yes, I guess. Could you try the branch `omni_tmp`, please?
