### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by epwalsh** [jalvesaq/Nvim-R#69]
Hi jalvesaq, first of all let me say that I am huge fan of this plugin and also vimcmdline. There is one thing I noticed when using this plugin: when knitting an Rmd file to a beamer presentation, for example, the resulting pdf is opened in a new window every time. It would be better if the pdf was only opened after the first time the file is knit. I realize I can set R_openpdf = 0 in my vimrc file, but then it won't open automatically when I first knit.

Thanks!

**Comment by jalvesaq** [comment]
What is your pdf viewer?

Valid values for R_openpdf are 0, 1 and 2 (or other higher integer). Please, see:
```
:h R_openpdf
```

**Comment by epwalsh** [comment]
Using skim. When R_openpdf is set to 1, it still opens every time I knit.

**Comment by jalvesaq** [comment]
I believe the bug is fixed now. Can you please confirm?

**Comment by epwalsh** [comment]
I am still getting the same issue

**Comment by jalvesaq** [comment]
The bug is fixed here. When `R_openpdf = 1`, the PDF is open only the first time I do `\kp`.

**Comment by epwalsh** [comment]
I am still having this problem when knitting an Rmd file to either (1) a pdf using `\kp` or (2) a beamer presentation using `\kl`

**Comment by jalvesaq** [comment]
It should be fixed now. Could you please try again?

**Comment by epwalsh** [comment]
Yes! I can confirm it's working. Thanks!
